# Generated by Django 5.1.1 on 2024-09-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_updated_at_alter_article_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("TR", "Trainee"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("CEO", "CEO"),
                        ],
                        default="TR",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
