# Generated by Django 5.1.1 on 2024-09-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_employee_created_at_employee_updated_at"),
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="category.category",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
